### ISSUE TITLE
Initialize Jupyter Book structure

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms-docs#2]
The idea here is to create an accessible user documentation (unlike the current developer documentation).
With Jupyter-Book this can simply be based on Jupyter notebooks.

As a start, I would just copy the existing tutorial notebooks to a `notebooks` folder and create a first draft book.

See:
- https://jupyterbook.org/en/stable/intro.html
- https://github.com/florian-huber/data_science_course

**Comment by julianpollmann** [comment]
Done with 0e55a80

**Comment by florian-huber** [comment]
Nice, thanks @julianpollmann !
