### ISSUE TITLE
Remove part x from title

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms-docs#7]
Currently the naming is not consistent. 
The first 3 notebooks start with Part 1, part 2, part 3. but the fourth notebook doesn't. Suggestion: remove part 1, part 2, part 3.

**Comment by niekdejonge** [comment]
I will also change some of the naming, to more clearly get a distinction between notebook 1 and 4.

**Comment by niekdejonge** [comment]
Nevermind. The three parts really belong together. At some point we should harmonize all four, so it becomes one continues tutorial. But for now I will leave it as is.

**Comment by julianpollmann** [comment]
Yes, harmonizing all parts seem to be useful. ALso some notebooks cover same aspects.
